apiVersion: apps/v1
# Deployment pre backend aplikáciu
kind: Deployment
metadata:
  name: backend
  namespace: zkt-notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
    # Backend kontajner používa Flask API
      containers:
        - name: backend
          image: z2-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: db-service
            - name: DB_NAME
              value: notesdb
            - name: DB_USER
              value: notesuser
            - name: DB_PASSWORD
              value: notessecret
            - name: DB_PORT
              value: "5432"
---
apiVersion: apps/v1
# Deployment pre frontend aplikáciu
kind: Deployment
metadata:
  name: frontend
  namespace: zkt-notes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
    # Frontend používa nginx server
      containers:
        - name: frontend
          image: z2-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80