apiVersion: v1
# Service pre frontend aplikáciu
kind: Service
metadata:
  name: frontend-service
  namespace: zkt-notes
spec:
# NodePort sprístupní frontend mimo Kubernetes clusteru
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
# Service pre backend komunikáciu
  name: backend-service
  namespace: zkt-notes
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
# Service pre PostgreSQL databázu
  name: db-service
  namespace: zkt-notes
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: db-headless
  namespace: zkt-notes
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432