apiVersion: v1
# PersistentVolume pre databázové dáta
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/zkt-notes-postgres
---
apiVersion: v1
# PersistentVolumeClaim pre pripojenie storage
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: zkt-notes
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
# StatefulSet pre PostgreSQL databázu
kind: StatefulSet
metadata:
  name: postgres
  namespace: zkt-notes
spec:
  serviceName: db-headless
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
          # PostgreSQL databáza beží na porte 5432
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: notesdb
            - name: POSTGRES_USER
              value: notesuser
            - name: POSTGRES_PASSWORD
              value: notessecret
              # Pripojenie persistent storage k databáze
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc